### **1. Trasformare cicli in list comprehension**

Fai tre esempi di cicli producono una lista e poi riscrivi lo stesso codice usando la list comprehension

In [4]:
##a - lista dei numeri pari da 0 a 14
pari = []
for n in range(15):
    if n%2 == 0:
        pari.append(n)
pariC = [n for n in range(15) if n%2==0]

print(pari)
print(pariC)


##b - lista con le stringhe più piccole di 5 caratteri di una lista di stringhe

stringhe = ["ciao", "arcobaleno", "gatto", "ape", "pace", "mano", "bicchiere" ]
minDi5 = []
for s in stringhe:
    if len(s) < 5:
        minDi5.append(s)
minDi5C = [s for s in stringhe if len(s) < 5]

print(minDi5)
print(minDi5C)

##c - lista dei cubi dei numeri da 0 a 9

cubi = []
for n in range(10):
    cubi.append(n**3)
cubiC = [n**3 for n in range(10)]

print(cubi)
print(cubiC)

[0, 2, 4, 6, 8, 10, 12, 14]
[0, 2, 4, 6, 8, 10, 12, 14]
['ciao', 'ape', 'pace', 'mano']
['ciao', 'ape', 'pace', 'mano']
[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]
[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]


### **2. Vettore di Numeri Primi**

1. **Crea un vettore** contenente tutti i numeri primi compresi tra **0 e 10**  
   _(Puoi scriverli direttamente nell'array)._

2. **Conta quanti numeri ci sono nel vettore** utilizzando la funzione `len()`.  **Ottieni lo stesso numero** accedendo all'attributo `.size` del vettore.

3. Quale pensi sia il tipo di dato (`dtype`) del vettore?  Prova a rispondere senza eseguire il codice e Verifica la tua risposta accedendo all'attributo `.dtype` del vettore

4. Scrivi l'array usando una list comprehension che controlla che i numeri siano primi. 

In [5]:
import numpy as np

primi = np.array([2, 3, 5, 7])

print(len(primi))
print(primi.size)
print(primi.dtype)

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, n):
        if n % i == 0:
            return False
    return True 
primiC = np.array([i for i in range(11) if is_prime(i)])

print(primiC)

4
4
int64
[2 3 5 7]


### **3.  Operazioni su array**
Crea un array **a**, 1D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente una sottostringa a piacere e **c** che è il reverse dell'array **a** (esempio [1,2,3] diventa [3,2,1]) .  Dividi l'array **a** per l'array **c**. Fai la stessa cosa per una lista.

In [6]:
import numpy as np

lista = [i for i in range(1,6)]

a = np.array(lista)
print(a)
b = a[3:6]
print(b)
c = a[::-1]
print(c)
print(a/c)

aa = lista.copy()
print(aa)
bb = a[3:6]
print(bb)
cc = aa[::-1]
print(cc)
#print(aa/cc) -> da errore

divisione = [aa[i]/cc[i] for i in range(len(aa))]
print(divisione)

[1 2 3 4 5]
[4 5]
[5 4 3 2 1]
[0.2 0.5 1.  2.  5. ]
[1, 2, 3, 4, 5]
[4 5]
[5, 4, 3, 2, 1]
[0.2, 0.5, 1.0, 2.0, 5.0]
